### ISSUE TITLE
Compiling from source

### ISSUE THREAD

**Issue by nikonikolov** [NVIDIA/nvidia-container-toolkit#200]
Can you please quickly let me know what is the right way to compile from source?

I tried doing something like
```
make binaries
DESTDIR=/
BINDIR=/usr/bin

install -d -m 755 ${DESTDIR}${BINDIR}
install -m 755 nvidia-container-runtime-hook ${DESTDIR}${BINDIR}
install -m 755 nvidia-ctk ${DESTDIR}${BINDIR}
```
Compilation works fine, both `nvidia-container-runtime-hook` and `nvidia-ctk` seem to run fine when invoked without any arguments and print the help message. However, when I run
```
docker run --gpus all a3204df90e0d nvidia-smi
```
I get a long error (see the log below).

When I replace `nvidia-container-runtime-hook` that I compiled from source with the one from the ubuntu `.deb` package, the above command works fine.

I am working with version 1.14.3. The reason I wanna compile from source is to add this package for Slackware Linux. 

Error log for `docker run --gpus all a3204df90e0d nvidia-smi` when it fails:
```
docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error running hook #0: error running hook: exit status 2, stdout: , stderr: SIGSEGV: segmentation violation
PC=0x0 m=0 sigcode=1
signal arrived during cgo execution

goroutine 1 [syscall]:
runtime.cgocall(0x52ccf0, 0xc0000f1680)
	/usr/lib64/go1.21.2/go/src/runtime/cgocall.go:157 +0x4b fp=0xc0000f1658 sp=0xc0000f1620 pc=0x40628b
github.com/NVIDIA/go-nvml/pkg/nvml._Cfunc_nvmlInit_v2()
	_cgo_gotypes.go:4597 +0x47 fp=0xc0000f1680 sp=0xc0000f1658 pc=0x51efc7
github.com/NVIDIA/go-nvml/pkg/nvml.nvmlInit_v2()
	/tmp/SBo/nvidia-container-toolkit-1.14.3/vendor/github.com/NVIDIA/go-nvml/pkg/nvml/nvml.go:32 +0x13 fp=0xc0000f1698 sp=0xc0000f1680 pc=0x51f913
github.com/NVIDIA/go-nvml/pkg/nvml.Init()
	/tmp/SBo/nvidia-container-toolkit-1.14.3/vendor/github.com/NVIDIA/go-nvml/pkg/nvml/init.go:43 +0x92 fp=0xc0000f16c0 sp=0xc0000f1698 pc=0x51f252
gitlab.com/nvidia/cloud-native/go-nvlib/pkg/nvml.(*nvmlLib).Init(0xc0000a34c0)
	/tmp/SBo/nvidia-container-toolkit-1.14.3/vendor/gitlab.com/nvidia/cloud-native/go-nvlib/pkg/nvml/nvml.go:39 +0x30 fp=0xc0000f16f8 sp=0xc0000f16c0 pc=0x521f10
github.com/NVIDIA/nvidia-container-toolkit/internal/info.additionalInfo.UsesNVGPUModule({{0x5a72e0, 0xc000098750}, {0x5a7c78, 0xc0000a34c0}, {0x5a7db8, 0xc0000d46c0}})
	/tmp/SBo/nvidia-container-toolkit-1.14.3/internal/info/additional_info.go:51 +0xcc fp=0xc0000f17c8 sp=0xc0000f16f8 pc=0x523a0c
github.com/NVIDIA/nvidia-container-toolkit/internal/info.(*additionalInfo).UsesNVGPUModule(0x570efe?)
	<autogenerated>:1 +0x59 fp=0xc0000f1838 sp=0xc0000f17c8 pc=0x524e39
github.com/NVIDIA/nvidia-container-toolkit/internal/info.resolver.resolveMode({{0x5a73b0?, 0x6c1e40?}, {0x5a7378?, 0xc00009f4a0?}}, {0x56db6e?, 0xc0000be500?}, 0x7?)
	/tmp/SBo/nvidia-container-toolkit-1.14.3/internal/info/auto.go:82 +0x29f fp=0xc0000f1910 sp=0xc0000f1838 pc=0x52457f
github.com/NVIDIA/nvidia-container-toolkit/internal/info.ResolveAutoMode({0x5a73b0, 0x6c1e40}, {0x56db6e, 0x4}, 0xc0000c02c0?)
	/tmp/SBo/nvidia-container-toolkit-1.14.3/internal/info/auto.go:60 +0x15c fp=0xc0000f19c8 sp=0xc0000f1910 pc=0x52421c
main.doPrestart()
	/tmp/SBo/nvidia-container-toolkit-1.14.3/cmd/nvidia-container-runtime-hook/main.go:85 +0x1ef fp=0xc0000f1ec8 sp=0xc0000f19c8 pc=0x527d6f
main.main()
	/tmp/SBo/nvidia-container-toolkit-1.14.3/cmd/nvidia-container-runtime-hook/main.go:175 +0x10a fp=0xc0000f1f40 sp=0xc0000f1ec8 pc=0x5290ea
runtime.main()
	/usr/lib64/go1.21.2/go/src/runtime/proc.go:267 +0x2bb fp=0xc0000f1fe0 sp=0xc0000f1f40 pc=0x4396fb
runtime.goexit()
	/usr/lib64/go1.21.2/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc0000f1fe8 sp=0xc0000f1fe0 pc=0x465f81

goroutine 2 [force gc (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/lib64/go1.21.2/go/src/runtime/proc.go:398 +0xce fp=0xc000048fa8 sp=0xc000048f88 pc=0x439b4e
runtime.goparkunlock(...)
	/usr/lib64/go1.21.2/go/src/runtime/proc.go:404
runtime.forcegchelper()
	/usr/lib64/go1.21.2/go/src/runtime/proc.go:322 +0xb3 fp=0xc000048fe0 sp=0xc000048fa8 pc=0x4399d3
runtime.goexit()
	/usr/lib64/go1.21.2/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc000048fe8 sp=0xc000048fe0 pc=0x465f81
created by runtime.init.6 in goroutine 1
	/usr/lib64/go1.21.2/go/src/runtime/proc.go:310 +0x1a

goroutine 3 [GC sweep wait]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/lib64/go1.21.2/go/src/runtime/proc.go:398 +0xce fp=0xc000049778 sp=0xc000049758 pc=0x439b4e
runtime.goparkunlock(...)
	/usr/lib64/go1.21.2/go/src/runtime/proc.go:404
runtime.bgsweep(0x0?)
	/usr/lib64/go1.21.2/go/src/runtime/mgcsweep.go:280 +0x94 fp=0xc0000497c8 sp=0xc000049778 pc=0x4261f4
runtime.gcenable.func1()
	/usr/lib64/go1.21.2/go/src/runtime/mgc.go:200 +0x25 fp=0xc0000497e0 sp=0xc0000497c8 pc=0x41b585
runtime.goexit()
	/usr/lib64/go1.21.2/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc0000497e8 sp=0xc0000497e0 pc=0x465f81
created by runtime.gcenable in goroutine 1
	/usr/lib64/go1.21.2/go/src/runtime/mgc.go:200 +0x66

goroutine 4 [GC scavenge wait]:
runtime.gopark(0xc000070000?, 0x5a50f8?, 0x1?, 0x0?, 0xc000007380?)
	/usr/lib64/go1.21.2/go/src/runtime/proc.go:398 +0xce fp=0xc000049f70 sp=0xc000049f50 pc=0x439b4e
runtime.goparkunlock(...)
	/usr/lib64/go1.21.2/go/src/runtime/proc.go:404
runtime.(*scavengerState).park(0x694360)
	/usr/lib64/go1.21.2/go/src/runtime/mgcscavenge.go:425 +0x49 fp=0xc000049fa0 sp=0xc000049f70 pc=0x423a89
runtime.bgscavenge(0x0?)
	/usr/lib64/go1.21.2/go/src/runtime/mgcscavenge.go:653 +0x3c fp=0xc000049fc8 sp=0xc000049fa0 pc=0x42401c
runtime.gcenable.func2()
	/usr/lib64/go1.21.2/go/src/runtime/mgc.go:201 +0x25 fp=0xc000049fe0 sp=0xc000049fc8 pc=0x41b525
runtime.goexit()
	/usr/lib64/go1.21.2/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc000049fe8 sp=0xc000049fe0 pc=0x465f81
created by runtime.gcenable in goroutine 1
	/usr/lib64/go1.21.2/go/src/runtime/mgc.go:201 +0xa5

goroutine 18 [finalizer wait]:
runtime.gopark(0x56a6a0?, 0x10043ac01?, 0x0?, 0x0?, 0x441d05?)
	/usr/lib64/go1.21.2/go/src/runtime/proc.go:398 +0xce fp=0xc000048628 sp=0xc000048608 pc=0x439b4e
runtime.runfinq()
	/usr/lib64/go1.21.2/go/src/runtime/mfinal.go:193 +0x107 fp=0xc0000487e0 sp=0xc000048628 pc=0x41a607
runtime.goexit()
	/usr/lib64/go1.21.2/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc0000487e8 sp=0xc0000487e0 pc=0x465f81
created by runtime.createfing in goroutine 1
	/usr/lib64/go1.21.2/go/src/runtime/mfinal.go:163 +0x3d

rax    0xc0000f2000
rbx    0xc0000f1680
rcx    0xc0000f1680
rdx    0xc0000f1610
rdi    0xc0000f1680
rsi    0x6945a0
rbp    0xc0000f1610
rsp    0x7ffd1f7cf698
r8     0x694980
r9     0x0
r10    0x7faeed84b310
r11    0x7faeed848d48
r12    0xc0000f2000
r13    0xaa5555
r14    0xc000006340
r15    0x36
rip    0x0
rflags 0x10206
cs     0x33
fs     0x0
gs     0x0: unknown.
time="2023-12-28T01:10:17+02:00" level=error msg="error waiting for container: "
```

**Comment by gabivlj** [comment]
I think you might be running into this issue:
https://github.com/NVIDIA/nvidia-container-toolkit/issues/113

Using go 1.20 will do the trick.

**Comment by ArangoGutierrez** [comment]
Hey @nikonikolov, please try with the go version as defined at the go mod https://github.com/NVIDIA/nvidia-container-toolkit/blob/main/go.mod#L3 , and you can use the helper scripts https://github.com/NVIDIA/nvidia-container-toolkit/blob/main/scripts/build-packages.sh 

I am closing this issue. If your build problem persist, please open a new issue.
